In [2]:
import numpy as np

# one-dimensional vector(1-d array)

In [4]:
# 以下两种方式声明的维度都一样
# numnpy默认使用的类型是float64
a = np.zeros(4)
print(a,a.shape,a.dtype)

b = np.zeros((4,))
print(b,b.shape,b.dtype)

[0. 0. 0. 0.] (4,) float64
[0. 0. 0. 0.] (4,) float64


In [6]:
c = np.random.random_sample(4)
print(c,c.shape,c.dtype)

d = np.random.rand(4)
print(d,d.shape,d.dtype)

[0.42021834 0.10088574 0.89881495 0.09204961] (4,) float64
[0.84795515 0.54863655 0.7716723  0.49411964] (4,) float64


In [8]:
e = np.arange(4) # 默认是int32
print(e,e.shape,e.dtype)

f = np.arange(4.) # 指定使用float64
print(f, f.shape, f.dtype)

[0 1 2 3] (4,) int32
[0. 1. 2. 3.] (4,) float64


In [10]:
g = np.array([5, 4, 3, 2])
print(g, g.shape, g.dtype)

h = np.array([5., 4, 3, 2]) # 所有值都变为float64
print(h, h.shape, h.dtype)

[5 4 3 2] (4,) int32
[5. 4. 3. 2.] (4,) float64


# 两个不同的一维数组

In [20]:
# show common Course 1 example
X = np.array([[1], [2], [3], [4]]) # X_train of dimension (m,n)
print(X,X.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)


In [21]:
e = np.arange(4) # 默认是int32
print(e,e.shape)


[0 1 2 3] (4,)


# 常见异常

## 索引越界

In [12]:
# indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
index 10 is out of bounds for axis 0 with size 4


## 维度不匹配

In [14]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f"Binary operators work element wise: {a + b}")

# try a mismatched vector operation
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

Binary operators work element wise: [0 0 6 8]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 
